// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyg79wQfyBPsRUbpPVnQHaHEB6s7ne5FY',
    appId: '1:110078271191:web:78a46fe6d1f00d47c7da92',
    messagingSenderId: '110078271191',
    projectId: 'premioscelo',
    authDomain: 'premioscelo.firebaseapp.com',
    storageBucket: 'premioscelo.appspot.com',
    measurementId: 'G-HGJTRV5M27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_NtO55jWQJElF-cHLvRYts1eXLKPuDYM',
    appId: '1:110078271191:android:ca1d75b3449a094ec7da92',
    messagingSenderId: '110078271191',
    projectId: 'premioscelo',
    storageBucket: 'premioscelo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbR-KLTTm2_t-RCAtx6xnwmSMg1jaxa5o',
    appId: '1:110078271191:ios:3ad03924dd2e2af1c7da92',
    messagingSenderId: '110078271191',
    projectId: 'premioscelo',
    storageBucket: 'premioscelo.appspot.com',
    iosBundleId: 'org.eurekamps.premiosCelo',
  );
}
